language: python
python:
    - "3.7"

install:
    - pip install poetry
    - poetry install
    - cp ci/travis-env .env

script:
    - pyflakes backend
    - poetry run flask db upgrade
    - poetry run python -m pytest
