---
language: python
dist: bionic
python:
    - "3.7"

install:
    - pip install poetry
    - poetry install
    - cp ci/travis-env .env

script:
    - pyflakes backend
    - poetry run flask db upgrade
    # test that schema changes are migrated
    - poetry run flask db migrate 2>&1 > /dev/null | grep 'No changes in schema detected.'
    - poetry run python -m pytest
