"""empty message

Revision ID: 0f49db3b8ad0
Revises: dbd2af3f0fad
Create Date: 2020-03-21 11:30:09.782555

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '0f49db3b8ad0'
down_revision = 'dbd2af3f0fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('shop', 'shops')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('shop', 'shops')
    # ### end Alembic commands ###
