"""empty message

Revision ID: b816e28f965b
Revises: 4e86b6077e49
Create Date: 2020-03-21 17:53:16.203078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b816e28f965b'
down_revision = '4e86b6077e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'users')
    op.create_table(
        'roles',
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint('name')
    )
    op.create_table(
        'user_roles',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('role_name', sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'role_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('users', 'user')
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
