"""empty message

Revision ID: dbd2af3f0fad
Revises: 
Create Date: 2020-03-21 11:27:53.967788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd2af3f0fad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('address', sa.UnicodeText(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
