"""empty message

Revision ID: e91038fb4a2d
Revises: b816e28f965b
Create Date: 2020-03-21 18:44:53.479224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91038fb4a2d'
down_revision = 'b816e28f965b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customer_datapoint',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('customers_inside', sa.Integer(), nullable=True),
        sa.Column('queue_size', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_datapoint')
    # ### end Alembic commands ###
